### ISSUE TITLE
MVP  Review

### ISSUE THREAD

**Issue by danemauland** [alisa1649/brainflayer#1]
Hey Alisa! This is a great first pass at the MVPs. I can tell you have a solid understanding of the main features of the app and you're focusing on all the right things. Most of my feeback just concerns fleshing out the details on a few things--I think this will help give you more direction when working on the project and will help employers who read your MVP list to have a better understanding of your project.

-Fill in the projected completion dates
 -Add production readme MVP
 New account creation:
 -These are a direct copy of the bluebird example. They need to be reworded to not be plagiarism.
 -Which features require users to be logged in?
-What does "Add User Auth , specifics" mean? I'm not sure you even need this bullet, I think the other points here, once reworded, will me sufficient for user auth
Decks & Cards
-Focus more on describing this from the user perspective. Although "Users can create, read, update, and delete decks" is all part of CRUD, reading vs creating/updating decks will be two different experiences for the user. Same for cards.
Dashboard
-What does "their decks" mean? Decks they created? Decks they're subscribed to? Both? If both, will they be combined in the same list, or will you have one list for created decks and one list for subscribed decks?
Search
-You can break this into two bullet points, e.g. "Users can search for decks across the site/The search query will be matched against the deck category and/or title"
-Would the search query be matched against just categories, or tags and categories?

**Comment by alisa1649** [comment]
Thank you for the feedback! I've made the changes.

**Comment by danemauland** [comment]
One last thing: Add a production README MVP for your 7th MVP. Completion date will be next Friday. No bullet points needed for this one.
