### ISSUE TITLE
Schema Review

### ISSUE THREAD

**Issue by danemauland** [alisa1649/brainflayer#2]
Great work on the schema! It's well thought-out and as-is would work for your project. There's just a little more information I would like to see added, and there are a couple potential improvements (depending on the nature of the table relationships):

-Describe each relationship (one-to-one, one-to-many, many-to-many, etc)
Decks
-Can decks have multiple tags? If so, consider creating a joins table to support the many-to-many relationship. If not., disregard this.
Tags
-Mention below the table that this is where "categories" lives and they're accessed using a self-join.
-Are users able to create new categories/are you considering adding this as a bonus feature? If not, and if each deck can only be in one category, you wouldn't need a self join and could just have a "category" column.

**Comment by alisa1649** [comment]
Thank you for the helpful feedback! I've made the changes to this MVP.

**Comment by danemauland** [comment]
I believe we discussed moving tags to be just a column in decks, please incorporate that change into your schema
