### ISSUE TITLE
Sample State Review

### ISSUE THREAD

**Issue by danemauland** [alisa1649/brainflayer#3]
Overall, good job on the sample state! A few things to consider:

Decks
 -Where are the icon_urls stored?
 Tags
 -If you're displaying the tags at any point, you will need the information stored somewhere in the state
Users
-It's not clear to me that you need a users slice of state. Your MVPs don't list any interaction between users or the ability to view other users' show page. If you want to display the auther of each deck, you should then take in a username and display that instead of their email, so you aren't giving out your users' contact info.

I love the card/deck examples you came up with!

**Comment by alisa1649** [comment]
Thank you for the feedback! I deleted the users slice, added state for tags and added the icon urls.

**Comment by danemauland** [comment]
If you're just using the the asset paths as placeholders, that's fine, but keep in mind that the paths to the assets will change since rails precompiles them. Review section 4 in the "deploying to heroku" materials for guidance on how to get these paths to the frontend.
