### ISSUE TITLE
Backend Routes Review

### ISSUE THREAD

**Issue by danemauland** [alisa1649/brainflayer#6]
Great work on your backend routes! The overall structure is great and would work, but here are some suggestions for improvement:

Decks
-Are you planning on needing having a page displaying all decks created? If so, GET /api/decks should return all decks and you should use a separate route for detting all the decks for the current user. If you are not going to be displaying all decks at once, then this is fine.
-Format your search route to use a query string instead of a wildcard, which is the convention for querying. I'd imagine the query string would look something like ?tag=react&title=integrating%20with%20%redux, where the tag and title keys are optional
Cards
-GET: consider making this a GET request to /decks/:id, which would return all the information about a deck (e.g. name, tag, etc.) AND all the cards belonging to that deck. This way, if a user goes directly to a deck, you don't have to make two separate API requests.
-PATCH/DELETE: if you have the card's id, what purpose does including the deck_id serve?

**Comment by alisa1649** [comment]
Thanks Dane! I don't plan on having a page to show all the decks, so I left the decks GET request as is. Good point about the search routes, I made the update. I also made the last two updates you suggested.
