### ISSUE TITLE
Frontend Routes Review

### ISSUE THREAD

**Issue by danemauland** [alisa1649/brainflayer#7]
Alisa, you did a fantastic job thinking through your components' structure. Doing so requires the ability to think abstractly about React, which shows a solid understanding of React's structure. Your routes capture the essence of what you want to use them for, but I have a few ideas to simplify them:

Optional - remove /dashboard/ and have logic for your root route that checks to see if a user is logged in. If the user is logged in, in renders the dashboard component. If the user is not logged in, it would render the splash page components
/dashboard/:deckId
-This works as-is. Consider making it dashboard/deck/:deckId or deck/:deckId just to make it a little more semantinc, but this is optional.

What's the difference between /dashboard/:deckId which has a DeckShow Component that renders CardItem, and /decks/:deckId/cards/show that also shows cards? It seems like there's a large duplication of work between the two

Tags
/tags/index can just be /tags
/tags/:tagId/show can just be /tags/:tagId

Search
-Let's discuss whether you need another route for SearchForm

**Comment by alisa1649** [comment]
Thanks so much for the positive comments :) 

* On the actual site, it's possible for a logged in user to view the splash page, so I left this as a route. 
* I made changes to the deck route and the tag index route
* The CardShow component is for studying, and the DeckShow component is for summarizing the deck information and cards it contains
